export const CATEGORIES = [
  "fruit",
  "vegetables",
  "dairy",
  "eggs",
  "meat",
  "fish_seafood",
  "vegetarian_vegan",
  "bakery",
  "breakfast",
  "pantry",
  "canned_jarred",
  "sauces_condiments",
  "herbs_spices",
  "snacks",
  "drinks",
  "frozen",
  "household",
  "cleaning",
  "personal_care",
  "baby_kids",
  "pet_supplies",
  "other",
] as const;

export type Category = (typeof CATEGORIES)[number];
export type CategoryKey = Category;

export const STORES = [
  "Albert Heijn",
  "Jumbo",
  "Lidl",
  "Aldi",
  "Kruidvat",
  "Action",
  "Local store",
  "Other",
] as const;

const CATEGORY_SET = new Set<string>(CATEGORIES);

const LEGACY_CATEGORY_TO_KEY: Record<string, CategoryKey> = {
  "Fruit & Vegetables": "vegetables",
  Dairy: "dairy",
  "Meat & Fish": "meat",
  Bakery: "bakery",
  Drinks: "drinks",
  Frozen: "frozen",
  Pantry: "pantry",
  Snacks: "snacks",
  Household: "household",
  "Personal Care": "personal_care",
  Other: "other",
};

export function categoryStoredValue(key: CategoryKey): CategoryKey {
  return key;
}

export function categoryKeyFromStored(stored: string | null | undefined): CategoryKey {
  if (!stored) return "other";
  const trimmed = stored.trim();
  if (CATEGORY_SET.has(trimmed)) return trimmed as CategoryKey;
  return LEGACY_CATEGORY_TO_KEY[trimmed] ?? "other";
}

const CATEGORY_KEYWORDS: Record<CategoryKey, string[]> = {
  fruit: [
    "aardbei",
    "aardbeien",
    "appel",
    "appels",
    "apple",
    "apples",
    "avocado",
    "banana",
    "bananas",
    "banaan",
    "bananen",
    "berries",
    "berry",
    "blauwe bes",
    "blauwe bessen",
    "blueberries",
    "blueberry",
    "citroen",
    "citroenen",
    "druif",
    "druiven",
    "grape",
    "grapes",
    "kiwi",
    "lemon",
    "lime",
    "mango",
    "orange",
    "oranges",
    "peer",
    "peren",
    "pineapple",
    "sinaasappel",
    "sinaasappels",
    "strawberries",
    "strawberry",
    "watermelon",
  ],
  vegetables: [
    "aardappel",
    "aardappelen",
    "aubergine",
    "bell pepper",
    "bloemkool",
    "broccoli",
    "cauliflower",
    "carrot",
    "carrots",
    "courgette",
    "cucumber",
    "garlic",
    "komkommer",
    "knoflook",
    "lettuce",
    "mushroom",
    "mushrooms",
    "onion",
    "onions",
    "paprika",
    "pepper",
    "peppers",
    "potato",
    "potatoes",
    "sla",
    "spinach",
    "spinazie",
    "tomaat",
    "tomaten",
    "tomato",
    "tomatoes",
    "ui",
    "uien",
    "wortel",
    "wortels",
    "zucchini",
  ],
  dairy: [
    "boter",
    "butter",
    "cheese",
    "creme fraiche",
    "crème fraîche",
    "dairy milk",
    "full fat milk",
    "halfvolle melk",
    "kaas",
    "kwark",
    "magere melk",
    "melk",
    "milk",
    "room",
    "slagroom",
    "volle melk",
    "vla",
    "yoghurt",
    "yogurt",
  ],
  eggs: ["ei", "eieren", "egg", "eggs"],
  meat: [
    "bacon",
    "beef",
    "chicken",
    "chicken breast",
    "gehakt",
    "ham",
    "kip",
    "kipfilet",
    "mince",
    "minced beef",
    "pork",
    "rundvlees",
    "spek",
    "turkey",
    "varkensvlees",
    "worst",
    "sausage",
  ],
  fish_seafood: [
    "cod",
    "fish",
    "garnalen",
    "haring",
    "kabeljauw",
    "salmon",
    "seafood",
    "shrimp",
    "tonijn",
    "tuna",
    "vis",
    "zalm",
  ],
  vegetarian_vegan: [
    "falafel",
    "hummus",
    "plantaardig",
    "seitan",
    "soja",
    "soy",
    "tempeh",
    "tofu",
    "vegan",
    "veganistisch",
    "vegetarian",
    "vegetarisch",
    "vegaburger",
    "vega burger",
  ],
  bakery: [
    "bagel",
    "bagels",
    "baguette",
    "beschuit",
    "bolletje",
    "bolletjes",
    "bread",
    "brood",
    "bun",
    "buns",
    "cracker",
    "crackers",
    "croissant",
    "croissants",
    "krentenbol",
    "krentenbollen",
    "pita",
    "rolls",
    "stokbrood",
    "tortilla",
    "tortillas",
    "volkoren brood",
    "wrap",
    "wraps",
  ],
  breakfast: [
    "brinta",
    "cereal",
    "cornflakes",
    "cruesli",
    "granola",
    "havermout",
    "muesli",
    "oatmeal",
    "oats",
    "ontbijtgranen",
    "porridge",
  ],
  pantry: [
    "bloem",
    "flour",
    "honey",
    "jam",
    "lentils",
    "macaroni",
    "noedels",
    "noodles",
    "olie",
    "olive oil",
    "olijfolie",
    "pasta",
    "peanut butter",
    "pindakaas",
    "rijst",
    "rice",
    "spaghetti",
    "suiker",
    "sugar",
  ],
  canned_jarred: [
    "beans",
    "blik tomaten",
    "canned",
    "chickpeas",
    "doperwten blik",
    "jarred",
    "kikkererwten",
    "mais blik",
    "pot augurken",
    "pot bonen",
    "pot groenten",
    "soep",
    "soup",
    "tomaten blik",
    "tomatoes canned",
  ],
  sauces_condiments: [
    "azijn",
    "bbq sauce",
    "dressing",
    "ketchup",
    "mayo",
    "mayonnaise",
    "mosterd",
    "mustard",
    "saus",
    "sauces",
    "sojasaus",
    "soy sauce",
    "tomatensaus",
    "vinegar",
  ],
  herbs_spices: [
    "basil",
    "basilicum",
    "cinnamon",
    "curry",
    "herbs",
    "kaneel",
    "komijn",
    "kruiden",
    "oregano",
    "paprikapoeder",
    "peper",
    "pepper",
    "salt",
    "specerijen",
    "spice",
    "spices",
    "zout",
  ],
  snacks: [
    "biscuits",
    "borrelnoot",
    "borrelnoten",
    "candy",
    "chips",
    "chocolate",
    "chocolade",
    "cookie",
    "cookies",
    "crisps",
    "koek",
    "koekje",
    "koekjes",
    "nootjes",
    "nuts",
    "popcorn",
    "snoep",
  ],
  drinks: [
    "appelsap",
    "beer",
    "bier",
    "chocolademelk",
    "chocolate milk",
    "cola",
    "coffee",
    "frisdrank",
    "ice tea",
    "ijsthee",
    "juice",
    "koffie",
    "lemonade",
    "sap",
    "sinaasappelsap",
    "soda",
    "tea",
    "thee",
    "water",
    "wijn",
    "wine",
  ],
  frozen: [
    "diepvries",
    "diepvriesgroenten",
    "diepvriespizza",
    "frikandel",
    "frikandellen",
    "friet",
    "frozen",
    "ice cream",
    "icecream",
    "ijs",
    "kroket",
    "kroketten",
    "patat",
    "pizza",
  ],
  household: [
    "aluminiumfolie",
    "batteries",
    "batterijen",
    "bin bag",
    "bin bags",
    "foil",
    "garbage bag",
    "garbage bags",
    "keukenpapier",
    "keukenrol",
    "paper towel",
    "paper towels",
    "toilet paper",
    "toiletpapier",
    "trash bag",
    "trash bags",
    "vuilniszak",
    "vuilniszakken",
    "wc papier",
    "wc-papier",
  ],
  cleaning: [
    "afwasmiddel",
    "allesreiniger",
    "bleach",
    "cleaner",
    "cleaning spray",
    "detergent",
    "dish soap",
    "dishwasher tablet",
    "dishwasher tablets",
    "schoonmaakmiddel",
    "sponge",
    "sponzen",
    "vaatwastablet",
    "vaatwastabletten",
    "wasmiddel",
  ],
  personal_care: [
    "conditioner",
    "deodorant",
    "douchegel",
    "lotion",
    "maandverband",
    "pads",
    "razor",
    "scheermesje",
    "scheermesjes",
    "shampoo",
    "soap",
    "tampon",
    "tampons",
    "tandpasta",
    "toothpaste",
    "zeep",
  ],
  baby_kids: [
    "baby wipes",
    "billendoekjes",
    "diaper",
    "diapers",
    "flesvoeding",
    "luiers",
    "nappies",
    "speen",
    "spenen",
    "wipes",
  ],
  pet_supplies: [
    "cat food",
    "dog food",
    "hondenvoer",
    "kattenbakvulling",
    "kattenvoer",
    "pet food",
    "poepzakjes",
  ],
  other: [],
};

const CONTAINER_OR_FILLER_WORDS = new Set([
  "bag",
  "bottle",
  "box",
  "doos",
  "fles",
  "pack",
  "pakken",
  "pak",
  "roll",
  "rollen",
  "rolls",
  "stuk",
  "stuks",
  "tray",
  "zak",
]);

function normalizeText(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .split(/\s+/)
    .filter((token) => token && !isIgnoredToken(token))
    .join(" ")
    .trim();
}

function isIgnoredToken(token: string) {
  return (
    CONTAINER_OR_FILLER_WORDS.has(token) ||
    /^\d+(?:[.,]\d+)?(?:x|g|gr|gram|kg|ml|cl|l|liter|litre|st|pcs)?$/i.test(token)
  );
}

function escapeRegex(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const MATCHERS = Object.entries(CATEGORY_KEYWORDS)
  .flatMap(([category, words]) =>
    words.map((word) => ({
      category: category as CategoryKey,
      keyword: normalizeText(word),
    })),
  )
  .filter(({ keyword }) => keyword.length > 0)
  .sort((a, b) => b.keyword.length - a.keyword.length);

export function suggestCategory(name: string): CategoryKey {
  const normalized = normalizeText(name);
  if (!normalized) return "other";

  for (const { category, keyword } of MATCHERS) {
    const re = new RegExp(`(^|\\s)${escapeRegex(keyword)}($|\\s)`, "u");
    if (re.test(normalized)) return category;
  }

  return "other";
}
